### ISSUE TITLE
Stream of 'v's after ctrl-amiga-amiga

### ISSUE THREAD

**Issue by jtsiomb** [jtsiomb/a500kbd#1]
For some reason after resetting the amiga with the ctrl-amiga-amiga combination, some times the keyboard controller starts sending a stream of 'v' keycodes to the system until another key is pressed.

**Comment by Quantum-cross** [comment]
I get the same thing but instead I get the backtick ` character (A600)

**Comment by jtsiomb** [comment]
I didn't bother with this because I was too lazy to open my amiga again and flash new firmware, but that's no reason to keep you waiting. I did a few changes which I think might solve the problem. If you get around to trying it, please let me know if it does.

**Comment by Quantum-cross** [comment]
Hey, I tried out the new commit, it doesn't seem to change anything. Maybe tomorrow I will try and do some debugging if I can figure out how to use a spare arduino as a serial interface.

**Comment by jtsiomb** [comment]
Merged Quantum-cross' pull request, which solves this issue.
