### ISSUE TITLE
Tested on an Amiga 600!

### ISSUE THREAD

**Issue by Quantum-cross** [jtsiomb/a500kbd#2]
Just wanted to let you know that I've tested this code on an Amiga 600. I soldered directly to the KB_CLOCK and KB_DATA lines.

You can go ahead and add that into the readme or whatever.

Thank you so much for developing this!!!

Now I have a numpad on the A600 :)

**Comment by jtsiomb** [comment]
Excellent! Glad to hear it, thanks for letting me know. I've added the info to the readme file, and I'm closing this as it's not really an "issue". An email would be preferable :)

**Comment by Quantum-cross** [comment]
Sorry, I didn't see the email in the readme, whoops!
